prometheus:
  prometheusSpec:
    retention: 30d
    resources:
      requests:
        memory: "1Gi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "500m"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    additionalScrapeConfigs:
    - job_name: 'prometheus-app'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: prometheus-app
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: "8080"

grafana:
  adminPassword: admin
  adminUser: admin
  persistence:
    enabled: true
    size: 5Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    alertmanagerConfiguration:
      name: global-alertmanager-config 
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: 'null'
    receivers:
      - name: 'null'
  # Configurações específicas definidas em AlertmanagerConfig(s)
  # Ver: k8s/alertmanager-config.yaml

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
